defaults:
  - scope:
      path: ''
    values:
      layout: page
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" 
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio" 

collections:
  portfolio:
    output: true

colorsets: 
  - alpineblue
  - green
  - tomatored